site_name: {{cookiecutter.repo_name}}
site_description: {{cookiecutter.description}}
site_author: {{cookiecutter.author_name}}

#repo_url:

theme:
    name: 'material'
    locale: en
    font: false

nav:
    - Home: index.md

# WIP
#markdown_extensions:
#  - mkautodoc
#plugins:
#  - mkdocs-jupyter
